language: python
python:
  - "2.7"
# command to install dependencies
install:  pip install ansible==2.4
# command to run tests
script:
  - ansible-galaxy install -r requirements.yml -p ./roles
  - |
    for PLAYBOOK in *.yml
    do
    if [ "$PLAYBOOK" != "requirements.yml" ]; then
    ansible-playbook $PLAYBOOK --syntax-check
    fi
    done
notifications:
  slack: redhat:GhPEcNzYddt4Pf9OJW2wcyCK
